// Everything the toys can say. Kept in one place because the drawer, the
// corner and the stamp all draw from it and the voice has to match.

// What is written on the page of the book that fell off the shelf. Never the
// story, always the odd page you happen to land on.
export const PAGES = [
  'this page is blank. so is the one facing it.',
  'a list, in your handwriting, of everything you meant to do on a tuesday in 2019.',
  'the whole page is one word, repeated. the word is "anyway".',
  'chapter eleven. there was no chapter ten.',
  'a pressed flower, brown, and the shape of it on the facing page.',
  'someone has underlined a single "the" and written "!!!" beside it.',
  'the index. it lists only one entry: "everything, 4-297".',
  'a receipt used as a bookmark. eggs, twine, a small hammer.',
  'the diagram is very clear and explains nothing.',
  '"see appendix c." there is no appendix c.',
  'a phone number with no name. the area code no longer exists.',
  'four pages of footnotes to a sentence that was cut.',
  'the author would like you to know they were very tired.',
  'a coffee ring, perfectly round, over the only interesting paragraph.',
  'the margin says "no". you cannot tell what it is answering.',
  'a recipe. every quantity is "some".',
  'the last page, and the killer is never named.',
  'someone folded this corner down. they never came back for it.',
  'two pages stuck together. you decide not to.',
  'a map of a town, and the town has one street.',
  'the dedication: "for whoever finds this."',
  'a paragraph you have read four times and still have not read.',
  'in the back, a library card. the last date stamped is a friday.',
  'the errata slip. it is longer than the chapter.',
  'a drawing of a horse. it is not a good drawing of a horse.',
  'the sentence ends mid-',
  'a translation note apologising for the joke you just missed.',
  'the glossary defines "the" and stops.',
  'this copy is signed. by someone else entirely.',
  'a page number, and nothing else on the page.',
  '"continued overleaf." it is not.',
  'a boarding pass for a flight that left without you.',
  'the epigraph is a quote from a book that does not exist.',
  'the whole chapter takes place in a corridor.',
  'a shopping list, then a line, then a very short poem.',
  'somebody has corrected a typo, introducing a worse one.',
  'the acknowledgements thank forty people and then a dog.',
  'a table of contents for a different book.',
  'the ink has run. it was probably not important.',
  'a note to self: "ask about the thing." you never asked.',
  'the first line is the last line of the previous chapter.',
  'a bus ticket, and on the back, one word: "finally".',
  'the book falls open here every time. no idea why.',
  'a chapter titled "later". it is four lines long.',
  'someone has written "same" beside a paragraph about being tired.',
  'the illustration is upside down and better that way.',
  'a page torn out. the stub is still in the spine.',
  'this is where you stopped last time, too.',
]

export const COUNTED = [
  (n: number) => `you have pulled this book ${n} times.`,
  (n: number) => `${n} readings. no closer to the plot.`,
  (n: number) => `${n}. the spine is going.`,
  (n: number) => `${n} times, and it is still the same book.`,
  (n: number) => `at ${n} openings this counts as studying.`,
  (n: number) => `${n}. the shelf has noticed.`,
  (n: number) => `${n} and you have not finished a single one.`,
  (n: number) => `${n}. you have other books.`,
  (n: number) => `opened ${n} times, read zero times.`,
]

export const STAMP_WORDS = [
  'SEEN',
  'NOTED',
  'AGAIN?',
  'FINE',
  'LATE',
  'SURE',
  'HMM',
  'DENIED',
  'PENDING',
  'LOGGED',
  'WHY',
  'NO',
  'ENOUGH',
  'VOID',
  'APPROVED',
  'VETOED',
  'INTERESTING',
  'RECEIVED',
  'FILED',
  'REJECTED',
  'PROVISIONAL',
  'UNDER REVIEW',
  'ESCALATED',
  'INCONCLUSIVE',
  'SO BE IT',
  'IF YOU SAY SO',
  '8 BALL SAYS NO',
  'ASK AGAIN LATER',
  'OUTLOOK GOOD',
  "THAT'S WEIRD",
  'YEP!',
  'NOPE.',
  'NAH',
  'WOW',
  'AWESOME!',
  'HUGE',
  'BOLD',
  'OK THEN',
  'SLAY',
  'MID',
  'GO ON',
  'AT LAST',
  'ABOUT TIME',
  'FINALLY!',
  'NOT BAD',
  'TRUE',
  'ALLEGEDLY',
  'CITATION NEEDED',
  'PROBABLY FINE',
  'DO IT AGAIN',
  'ASTONISHING',
  'HISTORIC',
  'IMPECCABLE',
  'UNHINGED',
  'RECKLESS',
  'RESPECT',
  'EH',
  'MMM',
  'SEEN IT',
  'CLASSIC',
  'ILLEGAL',
  'BANNED',
  'TAXED',
  'CANONICAL',
  'FOR THE RECORD',
  'DULY NOTED',
  'STAMPED',
  'STOP STAMPING',
  'THAT IS THE STAMP',
]

// Never the same line twice running - the pools are big enough that a repeat
// reads as the thing being broken rather than random.
export function pickNot<T>(list: T[], last: T | null): T {
  if (list.length < 2) return list[0]
  let next = last as T
  while (next === last) next = list[Math.floor(Math.random() * list.length)]
  return next
}
